## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
 - windows
julia:
  - 1.3
#  - nightly
#matrix:
#  allow_failures:
#    - julia: nightly
# env:
  #- GROUP=Core
  #- GROUP=Features
  #- GROUP=NLME
  #- GROUP=NCA
notifications:
  email: false

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
script:
 - julia -e 'using Pkg; Pkg.update(); Pkg.instantiate(); Pkg.precompile()'

# after_success:
#   # push coverage results to Coveralls
#   - julia -e 'import Pkg; import Pumas; cd(joinpath(dirname(pathof(Pumas)), "..")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
#   # push coverage results to Codecov
#   - julia -e 'import Pkg; import Pumas; cd(joinpath(dirname(pathof(Pumas)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
